[package]
name = "evm-state-cache"
version = "0.1.0"
edition = "2021"

[dependencies]
primitive-types = "0.12"
lru = "0.12"
moka = { version = "0.12", features = ["sync"] }
dashmap = "5.5"
revm = { version = "9", features = ["std"], default-features = false, optional = true }
